spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meudb
    username: postgres
    password: senha123

  jpa:
    hibernate:
      ddl-auto: validate   # valida se a tabela bate com a entidade, mas não altera nada
    show-sql: true

